name: Release
on:
  push:
    branches:
      - master
    paths:
      - 'index.js'
      - 'typescript.js'
      - 'vue.js'
      - 'react.js'
      - 'package.json'
env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
jobs:
  deploy:
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: NPM Auth
        command: npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Install pnpm
        run: npm i pnpm@latest -g
      - name: Setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER
      - name: Install dependencies
        run: pnpm install
      - run: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
